# title of website
title: 医界导航

# description of website
description: githubworldjoker's navigation site

# favicon of website
favicon: "https://github.com/githubworldjoker.png?size=40"

# your website url
url: https://githubworldjoker.github.io/medicineworld/

# github profile url
github: "https://flowus.cn/share/db53be43-d938-49bf-a077-d9a03de88fa3"

# footer message
footer: © 2022-2023 希望这个导航能帮到你

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu
      - bing
content:
  categories:
    - name: 医学科普
      sites:
        - name: 就诊问问
          description: 较为全面的医学咨询平台
          url: https://ask.nocode.com/
        - name: 默沙东诊疗手册
          description: 专业医学科普网站
          url: https://www.msdmanuals.cn/home
        - name: 百科名医
          description: 适配手机的医学百科
          url: https://m.baikemy.com/v1/
        - name: 医脉通
          description: 医学新闻网站
          url: https://www.medlive.cn/
        - name: 丁香医生
          description: 经典医学科普网站
          url: https://dxy.com/
        - name: 用药助手
          description: 丁香园旗下药品科普网站
          url: https://drugs.dxy.cn/
        - name: 医学微视
          description: 医学科普视频平台
          url: https://www.mvyxws.com/
        - name: WebMD
          description: 国外权威医学科普网站
          url: https://www.webmd.com/
        - name: 中华医学会
          description: 国内医学交流平台
          url: https://www.cma.org.cn/
        - name: 中国疾控中心
          description: 国家官方疾控中心
          url: https://www.chinacdc.cn/
        - name: A+医学百科
          description: 在线医学百科全书
          url: http://www.a-hospital.com/w/%E9%A6%96%E9%A1%B5
        - name: 世界卫生组织
          description: 世卫官方网站
          url: https://www.who.int/zh
    - name: 体制学习
      sites:
        - name: 英语真题在线
          description: 专八，四六级，考研真题都有，质量很高
          url: https://zhenti.burningvocabulary.com/
        - name: 考试酷
          description: 各行业考试题库，医学题很多且在不断更新
          url: https://www.examcoo.com/
        - name: 在线英语听力室
          description: 包含各种类型的英语听力内容
          url: http://m.tingroom.com/
        - name: 雅思在线机考
          description: 英文界面的雅思在线练习平台
          url: http://mini-ielts.com/ 
        - name: 研招网
          description: 中国研究生招生信息网
          url: https://yz.chsi.com.cn/ 
        - name: 考研帮
          description: 词条性质的考研资料分享网站，质量多变
          url: http://download.kaoyan.com/ 
        - name: youzack英语
          description: 英语听力精听背单词神器
          url: https://www.youzack.com/
        - name: 柯林斯词典
          description: 内容及其全面的英语词典
          url: https://www.collinsdictionary.com/zh/
        - name: 大学资源网
          description: 里面有许多医学课程
          url: http://www.dxzy163.com/
    - name: 学术相关
      sites:
        - name: 中国知网
          description: 国内经典学术信息交流网站
          url: https://i.cnki.net/#/
        - name: 小鲸鱼文献
          description: 免费且全面的文献搜索引擎
          url: http://www.9312.net/#/
        - name: 万方数据
          description: 各行业学术信息平台
          url: https://www.wanfangdata.com.cn/index.html?index=true
        - name: OALib
          description: 较为全面的论文搜索平台
          url: https://www.oalib.com/
        - name: readpaper
          description: 论文学术讨论社区
          url: https://readpaper.com/
        - name: MDPI论坛
          description: 科研文章论坛，医学科类分得很细致
          url: https://www.mdpi.com/
        - name: 知网随问
          description: 学术相关知识搜索引擎
          url: https://qa.cnki.net/web/
       
