# title of website
title: 医界导航

# description of website
description: githubworldjoker's navigation site

# favicon of website
favicon: "https://github.com/githubworldjoker.png?size=40"

# your website url
url: https://githubworldjoker.github.io/medicineworld/

# github profile url
github: "https://flowus.cn/share/db53be43-d938-49bf-a077-d9a03de88fa3"

# footer message
footer: © 2022-2024 希望这个导航能帮到你   公众号：龙旗

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu
      - bing
content:
  categories:
    - name: 医学科普
      sites:
        - name: 就诊问问
          description: 较为全面的医学咨询平台
          url: https://ask.nocode.com/
        - name: 默沙东诊疗手册
          description: 专业医学科普网站
          url: https://www.msdmanuals.cn/home
        - name: 百科名医
          description: 适配手机的医学百科
          url: https://m.baikemy.com/v1/
        - name: 医脉通
          description: 医学新闻网站
          url: https://www.medlive.cn/
        - name: 丁香医生
          description: 经典医学科普网站
          url: https://dxy.com/
        - name: 用药助手
          description: 丁香园旗下药品科普网站
          url: https://drugs.dxy.cn/
        - name: 医学微视
          description: 医学科普视频平台
          url: https://www.mvyxws.com/
        - name: WebMD
          description: 国外权威医学科普网站
          url: https://www.webmd.com/
        - name: 中华医学会
          description: 国内医学交流平台
          url: https://www.cma.org.cn/
        - name: 中国疾控中心
          description: 国家官方疾控中心
          url: https://www.chinacdc.cn/
        - name: A+医学百科
          description: 在线医学百科全书
          url: http://www.a-hospital.com/w/首页
        - name: 世界卫生组织
          description: 世卫官方网站
          url: https://www.who.int/zh
        - name: 医学论坛
          description: 
          url: https://www.cmt.com.cn/
        - name: 爱爱医
          description:
          url: https://m.iiyi.com/lt/
    - name: 体制学习
      sites:
        - name: 英语真题在线
          description: 专八，四六级，考研真题都有，质量很高
          url: https://zhenti.burningvocabulary.com/
        - name: 考试酷
          description: 各行业考试题库，医学题很多且在不断更新
          url: https://www.examcoo.com/
        - name: 在线英语听力室
          description: 包含各种类型的英语听力内容
          url: http://m.tingroom.com/
        - name: 雅思在线机考
          description: 英文界面的雅思在线练习平台
          url: http://mini-ielts.com/ 
        - name: 研招网
          description: 中国研究生招生信息网
          url: https://yz.chsi.com.cn/ 
        - name: 考研帮
          description: 词条性质的考研资料分享网站，质量多变
          url: http://download.kaoyan.com/ 
        - name: youzack英语
          description: 英语听力精听背单词神器
          url: https://www.youzack.com/
        - name: 柯林斯词典
          description: 内容及其全面的英语词典
          url: https://www.collinsdictionary.com/zh/
        - name: 大学资源网
          description: 里面有许多医学课程
          url: http://www.dxzy163.com/
    - name: 学术相关
      sites:
        - name: 中国知网
          description: 国内经典学术信息交流网站
          url: https://i.cnki.net/#/
        - name: 小鲸鱼文献
          description: 免费且全面的文献搜索引擎
          url: http://www.9312.net/#/
        - name: 万方数据
          description: 各行业学术信息平台
          url: https://www.wanfangdata.com.cn/index.html?index=true
        - name: OALib
          description: 较为全面的论文搜索平台
          url: https://www.oalib.com/
        - name: readpaper
          description: 论文学术讨论社区
          url: https://readpaper.com/
        - name: MDPI论坛
          description: 科研文章论坛，医学科类分得很细致
          url: https://www.mdpi.com/
        - name: 知网随问
          description: 学术相关知识搜索引擎
          url: https://qa.cnki.net/web/
        - name: semantic
          description: 老牌论文搜索引擎，需要一定的英文基础
          url: https://www.semanticscholar.org/
    - name: 发现应用
      sites:
        - name: Betalist
          description: 
          url: https://betalist.com/
        - name: slant
          description: 
          url: https://www.slant.co/
        - name: 前方软件站
          description: 
          url: https://qianfangzy.com/
        - name: 小众软件站
          description: 
          url: https://www.appinn.com/
        - name: 发现小众
          description: 
          url: https://meta.appinn.net/
        - name: 最美应用
          description: 
          url: http://zuimeia.com/
        - name: 少数派
          description: 
          url: https://sspai.com/
        - name: 创造者日报
          description: 
          url: https://creatorsdaily.com/
        - name: 新趣集
          description: 
          url: https://xinquji.com/
        - name: IT之家
          description: 
          url: https://soft.ithome.com/
        - name: V2EX发现
          description: 
          url: https://v2ex.com/go/share
        - name: alternativeto
          description: 
          url: https://alternativeto.net/
        - name: sourceforge
          description: 
          url: https://sourceforge.net/
        - name: filehippo
          description: 
          url: https://filehippo.com/
        - name: makeuseof
          description: 
          url: https://www.makeuseof.com/
        - name: lifehacker
          description: 
          url: https://lifehacker.com/   
        - name: 52破解
          description: 
          url: https://www.52pojie.cn/
        - name: 卡饭论坛
          description: 
          url: https://bbs.kafan.cn/
        - name: 学破解
          description: 
          url: https://www.xuepojie.com/
        - name: 远景论坛
          description: 
          url: https://bbs.pcbeta.com/
        - name: 乐愚社区
          description: 
          url: https://bbs.leyuz.net/
    - name: 各类导航
      sites:
        - name: 酷站吧
          description: 
          url: http://www.kuz8.com/index.php
        - name: 小鲸鱼搜书
          description: 
          url: http://www.9871.org/
        - name: 沙雕导航
          description: 
          url: https://shadiao.app/
        - name: 福利吧导航
          description: 
          url: https://fuliba123.net/
        - name: 智酷导航
          description: 
          url: https://www.wisecoco.com/
        - name: 聚收集导航
          description: 
          url: https://www.sjsdhw.com/
        - name: imyshare
          description: 
          url: https://imyshare.com/
        - name: 资源帝
          description: 
          url: http://shu.ziyuandi.cn/
        - name: 趣导航
          description: 
          url: https://ifun.cool/
        - name: 集知盒子
          description: 
          url: https://www.jizhihezi.com/
        - name: GF导航
          description: 
          url: https://www.gatherfind.com/
        - name: 一为导航
          description: 
          url: http://nav.iowen.cn/
        - name: 大佬导航
          description: 
          url: https://dalao.ru/2019/
        - name: 极梦小屋
          description: 
          url: https://www.jimeng365.cn/
        - name: 一纳米导航
          description: 
          url: http://m.1nami.com/
        - name: 麒麟摆渡
          description: 
          url: https://70bd.com/  
        - name: 效率集
          description: 
          url: http://www.xiaolvji.com/
        - name: 果汁导航
          description: 
          url: http://guozhivip.com/
        - name: 大数据导航
          description: 
          url: http://hao.199it.com/
        - name: 西西导航
          description: 
          url: https://www.xixiurl.com/
        - name: 黑导航
          description: 
          url: https://heidh.com/
        - name: 博客大全
          description: 
          url: https://blogwe.com/
        - name: addog
          description: 
          url: https://www.addog.vip/
        - name: 前站导航
          description: 
          url: http://www.frontendjs.com/
        - name: scihub导航
          description: 
          url: https://www.scihub.net.cn/
        - name: 产品导航
          description: 
          url: https://www.pmbaobao.com/#section-1
        - name: DAC导航
          description: 
          url: https://nwuzmed.ga/
        - name: 小呆导航
          description: 
          url: https://webjike.com/index.html
        - name: 紫花云
          description: 
          url: https://zihuayun.com/
        - name: 笔点
          description: 
          url: https://www.bidianer.com/
        - name: 箱格
          description: 
          url: https://xianggee.com/
        - name: 资源兔
          description: 
          url: https://www.ziyuantu.com/
        - name: 蜗牛导航
          description: 
          url: https://box.yangwang.ltd/
        - name: 掌酷导航
          description: 
          url: https://www.zkdh.net/
        - name: up6导航
          description: 
          url: https://www.up-6.com/
        - name: 番喜导航
          description: 
          url: https://fxsh.com/
        - name: 马丁库
          description: 
          url: https://www.martinku.cn/ 
        - name: 挖宝狗
          description: 
          url: https://wabaogou.com/
        - name: aboutPPT
          description: 
          url: https://www.aboutppt.com/
        - name: 五花八门
          description: 
          url: http://lxqnsys.com/d/#/index
        - name: 思谷搜
          description: 
          url: https://siguso.com/navi/
        - name: 萌导航
          description: 
          url: https://www.moe123.net/        
        - name: 王朝235
          description: 
          url: https://www.wc235.com/
        - name: 不求人导航
          description: 
          url: https://www.bqrdh.com/
        - name: 流莺书签
          description: 
          url: https://alanhzw.github.io/
        - name: 优创任意门
          description: 
          url: http://www.ayouchuang.com/
        - name: 兰客书签
          description: 
          url: https://b.lackk.com/
        - name: jay资源库
          description: 
          url: https://www.lovejay.top/
        - name: 果汁实验室
          description: 
          url: http://guozhivip.com/lab/
        - name: 优聚集
          description: 
          url: https://ujuji.com/
        - name: 不死鸟
          description: 
          url: https://dalao.ru/
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
    - name: 搜索聚合
      sites:
        - name: 淘链客
          description: 
          url: https://toplinks.cc/s/
        - name: 化学搜索
          description: 
          url: https://m.chemicalbook.com/ProductIndex.aspx
        - name: 植物通
          description: 
          url: https://zhiwutong.com/
        - name: 淘声网
          description: 
          url: https://www.tosound.com/
        - name: 道客巴巴
          description: 
          url: https://www.doc88.com/
        - name: idata
          description: 
          url: https://www.cn-ki.net/
        - name: 搜漫搜索
          description: 
          url: https://www.soman.com/
        - name: 虫快搜
          description: 
          url: https://search.chongbuluo.com/
        - name: 化妆品搜索
          description: 
          url: https://www.cosdna.com/chs/
        - name: ehow
          description: 
          url: https://www.ehow.com/
        - name: 论坛大全
          description: 
          url: http://www.scyky.com/
        - name: 便民查询
          description: 
          url: https://www.bmcx.com/
        - name: 逗比世界
          description: 
          url: https://www.dbbqb.com/
        - name: 深度学术
          description: 
          url: https://xs.zidianzhan.net/
        - name: 找台词
          description: 
          url: http://www.zhaotaici.cn/index.html
        - name: 33台词
          description: 
          url: https://33.agilestudio.cn/  
        - name: 库问搜索
          description: 
          url: http://www.koovin.com/
        - name: 无追搜索
          description: 
          url: https://www.wuzhuiso.com/
        - name: 镝数聚
          description: 
          url: https://www.dydata.io/
        - name: 问答库
          description: 
          url: https://www.asklib.com/
        - name: wikihow
          description: 
          url: https://zh.wikihow.com/%E9%A6%96%E9%A1%B5
        - name: 木材数据库
          description: 
          url: https://www.wood-database.com/
        - name: 字体搜索
          description: 
          url: https://www.100font.com/
        - name: 恐龙数据库
          description: 
          url: https://dinosaurpictures.org/?source=giaoshou.com
        - name: 音效搜索
          description: 
          url: https://taira-komori.jpn.org/freesoundcn.html?source=giaoshou.com
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
    - name: 特色网站
      sites:        
        - name: 书签地球
          description: 
          url: https://www.bookmarkearth.com/
        - name: drrr聊天室
          description: 
          url: https://drrr.com/
        - name: 合集网
          description: 
          url: https://233heji.com/
        - name: 搜网通
          description: 
          url: https://www.s5t.com/
        - name: 阿虚同学
          description: 
          url: https://axutongxue.com/
        - name: similarto
          description: 
          url: https://www.similarto.us/
        - name: i3社区
          description: 
          url: https://www.i3zh.com/
        - name: 奇趣网站
          description: 
          url: https://fuun.fun/
        - name: app喵
          description: 
          url: https://www.appmiu.com/
        - name: 趣乐兔
          description: 
          url: https://funletu.com/
        - name: github
          description: 
          url: https://github.com/
        - name: 只读
          description: 
          url: https://www.rdonly.com/
        - name: 万物对比
          description: 
          url: https://versus.com/cn
        - name: 煎蛋
          description: 
          url: http://i.jandan.net/
        - name: 网上厨房
          description: 
          url: https://m.ecook.cn/
        - name: 快吧软件
          description: 
          url: http://www.fast8.cc/
        - name: greasyfork
          description: 
          url: https://greasyfork.org/zh-CN
        - name: 文叔叔
          description: 
          url: https://www.wenshushu.cn/
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
